version: '3.8'  # Use the appropriate version for your Docker Compose setup

services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 80:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - todo-app  # Assign the app service to the todo-app network

  mysql:
    image: mysql:8.0
    volumes:
      - ~/mysql/:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - todo-app  # Assign the mysql service to the todo-app network

networks:
  todo-app:  # Define the todo-app network
