services:
  app:
    build: 
      context: ./getting-started-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - todos-network

  app-readonly:
    image: kaikrd/app-readonly:latest
    ports:
      - "3001:3001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - todos-network

  mysql:
    image: mysql:8.0
    volumes:
      - ~/mysql/:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - todos-network

networks:
  todos-network:
    driver: bridge
